name: my_flutter_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.1+1
environment:
  sdk: ">=2.17.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  image_picker: ^0.8.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

